//Authentication
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const INVALID_USER = 'INVALID_USER';
export const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTHENTICATION_INPROGRESS = 'AUTHENTICATION_INPROGRESS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_INPROGRESS = 'PASSWORD_CHANGE_INPROGRESS';
export const PASSWORD_CHANGE_NOT_SUCCESS = 'PASSWORD_CHANGE_NOT_SUCCESS';
export const PASSWORD_CONNECTION_ERROR = 'PASSWORD_CONNECTION_ERROR';
export const REGISTRATION_INPROGRESS = 'REGISTRATION_INPROGRESS';
export const REGISTRATION_NOT_SUCCESS = 'REGISTRATION_NOT_SUCCESS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_COMPLETE = 'FORGOT_PASSWORD_COMPLETE';
export const CHECK_FORGOT_PASSWORD_SUCCESS = 'CHECK_FORGOT_PASSWORD_SUCCESS';
export const CHECK_FORGOT_PASSWORD_ERROR = 'CHECK_FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';


//ManageUser
export const USER_INPROGRESS = 'USER_INPROGRESS';
export const USER_CONNECTION_ERROR = 'USER_CONNECTION_ERROR';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_CHANGE_NOT_SUCCESS = 'USER_CHANGE_NOT_SUCCESS';
export const USER_BLOCK_SUCCESS = 'USER_BLOCK_SUCCESS';
export const USER_BLOCK_NOT_SUCCESS = 'USER_BLOCK_NOT_SUCCESS';

//ServiceManage
export const SERVICE_INPROGRESS = 'SERVICE_INPROGRESS';
export const SERVICE_CONNECTION_ERROR = 'SERVICE_CONNECTION_ERROR';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS';
export const SERVICE_ADD_SUCCESS = 'SERVICE_ADD_SUCCESS';
export const SERVICE_EDIT_SUCCESS = 'SERVICE_EDIT_SUCCESS';
export const SERVICE_NOT_SUCCESS = 'SERVICE_NOT_SUCCESS';

//TeamProductManage
export const PRODUCT_INPROGRESS = 'PRODUCT_INPROGRESS';
export const PRODUCT_CONNECTION_ERROR = 'PRODUCT_CONNECTION_ERROR';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const TEAM_MEMBER_PRODUCT_SUCCESS = 'TEAM_MEMBER_PRODUCT_SUCCESS';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_NOT_SUCCESS = 'PRODUCT_NOT_SUCCESS';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';

//SliderManage
export const SLIDER_INPROGRESS = 'SLIDER_INPROGRESS';
export const SLIDER_CONNECTION_ERROR = 'SLIDER_CONNECTION_ERROR';
export const SLIDER_SUCCESS = 'SLIDER_SUCCESS';
export const SLIDER_DELETE_SUCCESS = 'SLIDER_DELETE_SUCCESS';
export const SLIDER_ADD_SUCCESS = 'SLIDER_ADD_SUCCESS';
export const SLIDER_NOT_SUCCESS = 'SLIDER_NOT_SUCCESS';


//GalleryManage
export const GALLERY_INPROGRESS = 'GALLERY_INPROGRESS';
export const GALLERY_CONNECTION_ERROR = 'GALLERY_CONNECTION_ERROR';
export const GALLERY_SUCCESS = 'GALLERY_SUCCESS';
export const GALLERY_DELETE_SUCCESS = 'GALLERY_DELETE_SUCCESS';
export const GALLERY_ADD_SUCCESS = 'GALLERY_ADD_SUCCESS';
export const GALLERY_EDIT_SUCCESS = 'GALLERY_EDIT_SUCCESS';
export const GALLERY_NOT_SUCCESS = 'GALLERY_NOT_SUCCESS';


//TeamManage
export const TEAM_INPROGRESS = 'TEAM_INPROGRESS';
export const TEAM_CONNECTION_ERROR = 'TEAM_CONNECTION_ERROR';
export const TEAM_SUCCESS = 'TEAM_SUCCESS';
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS';
export const TEAM_ADD_SUCCESS = 'TEAM_ADD_SUCCESS';
export const TEAM_EDIT_SUCCESS = 'TEAM_EDIT_SUCCESS';
export const TEAM_NOT_SUCCESS = 'TEAM_NOT_SUCCESS';

//SOD
export const SOD_INPROGRESS = 'SOD_INPROGRESS';
export const SOD_CONNECTION_ERROR = 'SOD_CONNECTION_ERROR';
export const SOD_SUCCESS = 'SOD_SUCCESS';
export const SOD_NOT_SUCCESS = 'SOD_NOT_SUCCESS';
export const SOD_RUNNING_LATE_MOVE_TO_PROGRESS = 'SOD_RUNNING_LATE_MOVE_TO_PROGRESS';
export const SOD_RECENT_MOVE_TO_PROGRESS = 'SOD_RECENT_MOVE_TO_PROGRESS';


//Website
export const WEBSITE_INPROGRESS = 'WEBSITE_INPROGRESS';
export const WEBSITE_NOT_SUCCESS = 'WEBSITE_NOT_SUCCESS';
export const WEBSITE_CONNECTION_ERROR = 'WEBSITE_CONNECTION_ERROR';
export const ALL_GALLERY_SUCCESS = 'ALL_GALLERY_SUCCESS';
export const WEBSITE_HOME = 'WEBSITE_HOME';


