//Authentication
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const INVALID_USER = 'INVALID_USER';
export const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTHENTICATION_INPROGRESS = 'AUTHENTICATION_INPROGRESS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_INPROGRESS = 'PASSWORD_CHANGE_INPROGRESS';
export const PASSWORD_CHANGE_NOT_SUCCESS = 'PASSWORD_CHANGE_NOT_SUCCESS';
export const PASSWORD_CONNECTION_ERROR = 'PASSWORD_CONNECTION_ERROR';
export const REGISTRATION_INPROGRESS = 'REGISTRATION_INPROGRESS';
export const REGISTRATION_NOT_SUCCESS = 'REGISTRATION_NOT_SUCCESS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_COMPLETE = 'FORGOT_PASSWORD_COMPLETE';
export const CHECK_FORGOT_PASSWORD_SUCCESS = 'CHECK_FORGOT_PASSWORD_SUCCESS';
export const CHECK_FORGOT_PASSWORD_ERROR = 'CHECK_FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';


//ManageUser
export const USER_INPROGRESS = 'USER_INPROGRESS';
export const USER_CONNECTION_ERROR = 'USER_CONNECTION_ERROR';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_CHANGE_NOT_SUCCESS = 'USER_CHANGE_NOT_SUCCESS';

//SOD
export const SOD_INPROGRESS = 'SOD_INPROGRESS';
export const SOD_CONNECTION_ERROR = 'SOD_CONNECTION_ERROR';
export const SOD_SUCCESS = 'SOD_SUCCESS';
export const SOD_NOT_SUCCESS = 'SOD_NOT_SUCCESS';
export const SOD_RUNNING_LATE_MOVE_TO_PROGRESS = 'SOD_RUNNING_LATE_MOVE_TO_PROGRESS';
export const SOD_RECENT_MOVE_TO_PROGRESS = 'SOD_RECENT_MOVE_TO_PROGRESS';


//Website
export const WEBSITE_INPROGRESS = 'WEBSITE_INPROGRESS';
export const WEBSITE_NOT_SUCCESS = 'WEBSITE_NOT_SUCCESS';
export const WEBSITE_CONNECTION_ERROR = 'WEBSITE_CONNECTION_ERROR';
export const ALL_GALLERY_SUCCESS = 'ALL_GALLERY_SUCCESS';
export const WEBSITE_HOME = 'WEBSITE_HOME';


