//Authentication
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const IS_ALREADY_AUTHENTICATED = 'IS_ALREADY_AUTHENTICATED';
export const INVALID_USER = 'INVALID_USER';
export const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTHENTICATION_INPROGRESS = 'AUTHENTICATION_INPROGRESS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_INPROGRESS = 'PASSWORD_CHANGE_INPROGRESS';
export const PASSWORD_CHANGE_NOT_SUCCESS = 'PASSWORD_CHANGE_NOT_SUCCESS';
export const PASSWORD_CONNECTION_ERROR = 'PASSWORD_CONNECTION_ERROR';
export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_COMPLETE = 'FORGOT_PASSWORD_COMPLETE';
export const CHECK_FORGOT_PASSWORD_SUCCESS = 'CHECK_FORGOT_PASSWORD_SUCCESS';
export const CHECK_FORGOT_PASSWORD_ERROR = 'CHECK_FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';


//ManageUser
export const USER_INPROGRESS = 'USER_INPROGRESS';
export const USER_CONNECTION_ERROR = 'USER_CONNECTION_ERROR';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_CHANGE_NOT_SUCCESS = 'USER_CHANGE_NOT_SUCCESS';

//SOD
export const SOD_INPROGRESS = 'SOD_INPROGRESS';
export const SOD_CONNECTION_ERROR = 'SOD_CONNECTION_ERROR';
export const SOD_SUCCESS = 'SOD_SUCCESS';
export const SOD_NOT_SUCCESS = 'SOD_NOT_SUCCESS';
export const SOD_RUNNING_LATE_MOVE_TO_PROGRESS = 'SOD_RUNNING_LATE_MOVE_TO_PROGRESS';
export const SOD_RECENT_MOVE_TO_PROGRESS = 'SOD_RECENT_MOVE_TO_PROGRESS';


//DDSStartup
export const LOAD_DDS_DATA = 'LOAD_DDS_DATA';
export const LOAD_DDS_DATA_SUCCESS = 'LOAD_DDS_DATA_SUCCESS';
export const DDS_STARTUP_DATA = 'DDS_STARTUP_DATA';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const ORDER_DETAIL = 'ORDER_DETAIL';
export const INITIAL_ORDER_DETAIL = 'INITIAL_ORDER_DETAIL';
export const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
export const NOT_FOUND = 'NOT_FOUND';
export const RECENT_ORDERS = 'RECENT_ORDERS';
export const LOAD_RECENT_ORDERS = 'LOAD_RECENT_ORDERS';
export const DATA_RECEIVED = 'DATA_RECEIVED';
export const STORE_USER_AVATAR_UPLOAD_SUCCESS = 'STORE_USER_AVATAR_UPLOAD_SUCCESS';
export const ERROR_UPLOAD_USER_AVATAR = 'ERROR_UPLOAD_USER_AVATAR';
export const LOAD_CHAT_DATA = 'LOAD_CHAT_DATA';
export const LOAD_CHAT_DATA_SUCCESS = 'LOAD_CHAT_DATA_SUCCESS';
export const CHAT_STARTUP_DATA = 'CHAT_STARTUP_DATA';

export const CHAT_DETAIL = 'CHAT_DETAIL';
export const INITIAL_CHAT_DETAIL = 'INITIAL_CHAT_DETAIL';
export const CHAT_NOT_FOUND = 'CHAT_NOT_FOUND';

//Store Configuration
export const STORE_CONFIGURE_SUCCESS = 'STORE_CONFIGURE_SUCCESS';
export const ERROR_CONFIGURE_STORE = 'ERROR_CONFIGURE_STORE';
export const GET_ALL_STORES = 'GET_ALL_STORES';
export const LOADING_ALL_STORES = 'LOADING_ALL_STORES';
export const STORE_EDITED_SUCCESS = 'STORE_EDITED_SUCCESS';
export const ERROR_EDITED_STORE = 'ERROR_EDITED_STORE';
export const LOADING_USER = 'LOADING_USER';

//User Configuration
export const USER_CONFIGURE_SUCCESS = 'USER_CONFIGURE_SUCCESS';
export const ERROR_USER_CONFIGURE_STORE = 'ERROR_USER_CONFIGURE_STORE';
export const GET_ALL_USER_ROLES = 'GET_ALL_USER_ROLES';
export const GET_ALL_USER_ROLES_SUCCESS = 'GET_ALL_USER_ROLES_SUCCESS';
export const ERROR_GET_USER_ROLES = 'ERROR_GET_USER_ROLES';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const ERROR_GET_ALL_USERS = 'ERROR_GET_ALL_USERS';
export const USER_EDITED_SUCCESS = 'USER_EDITED_SUCCESS';
export const ERROR_EDITING_USER = 'ERROR_EDITING_USER';
export const CHANGE_VALUE_ERROR = 'CHANGE_VALUE_ERROR';

// Analytics
export const GET_ANALYTICS_DATA = 'GET_ANALYTICS_DATA';
export const GET_ANALYTICS_DATA_SUCCESS = 'GET_ANALYTICS_DATA_SUCCESS';
export const GET_ANALYTICS_DATA_ERROR = 'GET_ANALYTICS_DATA_ERROR';
export const GET_ANALYTICS_DATA_ALL_STORE = 'GET_ANALYTICS_DATA_ALL_STORE';
export const GET_ANALYTICS_DATA_SUCCESS_ALL_STORE = 'GET_ANALYTICS_DATA_SUCCESS_ALL_STORE';
export const GET_ANALYTICS_DATA_ERROR_ALL_STORE = 'GET_ANALYTICS_DATA_ERROR_ALL_STORE';
export const GET_ANALYTICS_DATA_AVG_WAIT_TIME = 'GET_ANALYTICS_DATA_AVG_WAIT_TIME';
export const GET_ANALYTICS_DATA_SUCCESS_AVG_WAIT_TIME = 'GET_ANALYTICS_DATA_SUCCESS_AVG_WAIT_TIME';
export const GET_ANALYTICS_DATA_ERROR_AVG_WAIT_TIME = 'GET_ANALYTICS_DATA_ERROR_AVG_WAIT_TIME';
export const GET_ANALYTICS_DATA_RATING = 'GET_ANALYTICS_DATA_RATING';
export const GET_ANALYTICS_DATA_SUCCESS_RATING = 'GET_ANALYTICS_DATA_SUCCESS_RATING';
export const GET_ANALYTICS_DATA_ERROR_RATING = 'GET_ANALYTICS_DATA_ERROR_RATING';
export const GET_ANALYTICS_DATA_TRANSPORT = 'GET_ANALYTICS_DATA_TRANSPORT';
export const GET_ANALYTICS_DATA_SUCCESS_TRANSPORT = 'GET_ANALYTICS_DATA_SUCCESS_TRANSPORT';
export const GET_ANALYTICS_DATA_ERROR_TRANSPORT = 'GET_ANALYTICS_DATA_ERROR_TRANSPORT';
export const GET_ANALYTICS_DATA_TICKET_STATS = 'GET_ANALYTICS_DATA_TICKET_STATS';
export const GET_ANALYTICS_DATA_SUCCESS_TICKET_STATS = 'GET_ANALYTICS_DATA_SUCCESS_TICKET_STATS';
export const GET_ANALYTICS_DATA_ERROR_TICKET_STATS = 'GET_ANALYTICS_DATA_ERROR_TICKET_STATS';
export const GET_ANALYTICS_DATA_REQUEST_BY_HOURS = 'GET_ANALYTICS_DATA_REQUEST_BY_HOURS';
export const GET_ANALYTICS_DATA_SUCCESS_REQUEST_BY_HOURS = 'GET_ANALYTICS_DATA_SUCCESS_REQUEST_BY_HOURS';
export const GET_ANALYTICS_DATA_ERROR_REQUEST_BY_HOURS = 'GET_ANALYTICS_DATA_ERROR_REQUEST_BY_HOURS';
export const GET_ANALYTICS_DATA_REQUEST_LOCATION_TRACKING = 'GET_ANALYTICS_DATA_REQUEST_LOCATION_TRACKING';
export const GET_ANALYTICS_DATA_SUCCESS_REQUEST_LOCATION_TRACKING = 'GET_ANALYTICS_DATA_SUCCESS_REQUEST_LOCATION_TRACKING';
export const GET_ANALYTICS_DATA_ERROR_REQUEST_LOCATION_TRACKING = 'GET_ANALYTICS_DATA_ERROR_REQUEST_LOCATION_TRACKING';
export const GET_ANALYTICS_DATA_REREQUEST_ORDER = 'GET_ANALYTICS_DATA_REREQUEST_ORDER';
export const GET_ANALYTICS_DATA_SUCCESS_REREQUEST_ORDER = 'GET_ANALYTICS_DATA_SUCCESS_REREQUEST_ORDER';
export const GET_ANALYTICS_DATA_ERROR_REREQUEST_ORDER = 'GET_ANALYTICS_DATA_ERROR_REREQUEST_ORDER';
export const GET_ANALYTICS_DATA_CANCELLED_REQUESTS = 'GET_ANALYTICS_DATA_CANCELLED_REQUESTS';
export const GET_ANALYTICS_DATA_SUCCESS_CANCELLED_REQUESTS = 'GET_ANALYTICS_DATA_SUCCESS_CANCELLED_REQUESTS';
export const GET_ANALYTICS_DATA_ERROR_CANCELLED_REQUESTS = 'GET_ANALYTICS_DATA_ERROR_CANCELLED_REQUESTS';
export const GET_ANALYTICS_DATA_TRANSPORT_TYPE_BY_DATE = 'GET_ANALYTICS_DATA_TRANSPORT_TYPE_BY_DATE';
export const GET_ANALYTICS_DATA_SUCCESS_TRANSPORT_TYPE_BY_DATE = 'GET_ANALYTICS_DATA_SUCCESS_TRANSPORT_TYPE_BY_DATE';
export const GET_ANALYTICS_DATA_ERROR_TRANSPORT_TYPE_BY_DATE = 'GET_ANALYTICS_DATA_ERROR_TRANSPORT_TYPE_BY_DATE';
export const GET_ANALYTICS_DATA_MOST_ACTIVE_CUSTOMERS = 'GET_ANALYTICS_DATA_MOST_ACTIVE_CUSTOMERS';
export const GET_ANALYTICS_DATA_SUCCESS_MOST_ACTIVE_CUSTOMERS = 'GET_ANALYTICS_DATA_SUCCESS_MOST_ACTIVE_CUSTOMERS';
export const GET_ANALYTICS_DATA_ERROR_MOST_ACTIVE_CUSTOMERS = 'GET_ANALYTICS_DATA_ERROR_MOST_ACTIVE_CUSTOMERS';
export const GET_ANALYTICS_DATA_MOST_ACTIVE_CUSTOMERS_ALL_STORES = 'GET_ANALYTICS_DATA_MOST_ACTIVE_CUSTOMERS_ALL_STORES';
export const GET_ANALYTICS_DATA_SUCCESS_MOST_ACTIVE_CUSTOMERS_ALL_STORES = 'GET_ANALYTICS_DATA_SUCCESS_MOST_ACTIVE_CUSTOMERS_ALL_STORES';
export const GET_ANALYTICS_DATA_ERROR_MOST_ACTIVE_CUSTOMERS_ALL_STORES = 'GET_ANALYTICS_DATA_ERROR_MOST_ACTIVE_CUSTOMERS_ALL_STORES';