const ENVIRONMENT_DEVELOPMENT = {
    API_URL: "http://192.168.200.18:9000/api"
};

const ENVIRONMENT_PRODUCTION = {
    API_URL: "http://192.168.200.18:9000/api"
};
let ENVIRONMENT_VARIABLES;
if (process.env.NODE_ENV === "development") {
    ENVIRONMENT_VARIABLES = ENVIRONMENT_DEVELOPMENT;
} else {
    ENVIRONMENT_VARIABLES = ENVIRONMENT_PRODUCTION;
}

export default ENVIRONMENT_VARIABLES;
